#!/bin/sh

case $1 in
	start)
		exit 0
	;;
	stop)
		exit 0
	;;
	status)
		exit 0
	;;
	log)
		echo "Config File Editor installed properly. To access it, click icon under 'admin' menu">/tmp/cfe.log
		echo "/tmp/cfe.log";
		exit 0
	;;
esac
                                     
